### ISSUE TITLE
Could not load any settings

### ISSUE THREAD

**Issue by LinWeiChin** [JulianeMu/explainable_cdss_for_therapy_planning#1]
Hello, I am a student of National Yunlin University of Science and Technology, and I downloaded your code and executed the program according to the procedure you gave, but the following problems occurred:
![螢幕擷取畫面 2021-01-28 201214](https://user-images.githubusercontent.com/78152679/106141144-ae355f00-61aa-11eb-9b20-5f75398c0e98.png)

The index.html could not load any js file, if you have any way can solve this problem please tell me.

**Comment by LinWeiChin** [comment]
I change the folder structure and the  code of index.html, like this picture
![螢幕擷取畫面 2021-01-28 201745](https://user-images.githubusercontent.com/78152679/106145743-dde76580-61b0-11eb-875a-14f88652bb59.png)
This change can load js files, but I have new promble now,
![螢幕擷取畫面 2021-01-28 215655](https://user-images.githubusercontent.com/78152679/106148299-daa1a900-61b3-11eb-9ae4-fc98c1a0af57.png)
![螢幕擷取畫面 2021-01-28 215724](https://user-images.githubusercontent.com/78152679/106148305-dd040300-61b3-11eb-98b9-51b8c0c5c90c.png)
The red part can not use, if you have any way can solve this problem please tell me, thank you.

**Comment by JulianeMu** [comment]
Hello,

thanks for using my code! 

Could you please give me some more information? What's written in the browser console output and in the backend console output?

All the best,
Juliane

**Comment by LinWeiChin** [comment]
Before I change the folder structure and the code of index.html, 
the browser console output is
![螢幕擷取畫面 2021-01-29 121824](https://user-images.githubusercontent.com/78152679/106231505-d4034800-622c-11eb-8c60-e42279b47cff.png)
![螢幕擷取畫面 2021-01-29 121851](https://user-images.githubusercontent.com/78152679/106231521-db2a5600-622c-11eb-8fee-e8b2d5a4d3a9.png)
![螢幕擷取畫面 2021-01-29 121940](https://user-images.githubusercontent.com/78152679/106231524-dcf41980-622c-11eb-817e-8a82dd7ea213.png)
![螢幕擷取畫面 2021-01-29 122003](https://user-images.githubusercontent.com/78152679/106231527-de254680-622c-11eb-858c-3db86ab9211d.png)
and the backend console output is
![螢幕擷取畫面 2021-01-29 121657](https://user-images.githubusercontent.com/78152679/106231602-0745d700-622d-11eb-88e5-51ae76273667.png)
![螢幕擷取畫面 2021-01-29 121740](https://user-images.githubusercontent.com/78152679/106231617-0dd44e80-622d-11eb-9779-e637e5926fa5.png)

After I change
the browser console output is
![螢幕擷取畫面 2021-01-29 123649](https://user-images.githubusercontent.com/78152679/106232392-e2526380-622e-11eb-87a8-ba14f83e0700.png)
the backend console output is
![螢幕擷取畫面 2021-01-29 123722](https://user-images.githubusercontent.com/78152679/106232601-5ab92480-622f-11eb-9663-d04c6011d443.png)
![螢幕擷取畫面 2021-01-29 123759](https://user-images.githubusercontent.com/78152679/106232605-5db41500-622f-11eb-8534-ca31e66ee1da.png)

**Comment by JulianeMu** [comment]
Thanks for the response! How did you change the folder structure and why? How was it before and how is it now? 
This changed folder structure also has an impact on the new error message. For this, please go to  
`explainable_cdss_for_therapy_planning/templates/structured_exploration/structured_exploration.html`
and check for the correct folder structure and links.
